### ISSUE TITLE
URL prefix

### ISSUE THREAD

**Issue by gitpushdashf** [public/sonora#40]
Thank you again for your help so far. We're starting to test Sonora internally now.

Is there a good way to have some kind of a prefix on the endpoints? Like `/grpc/` or `/api/`?

**Comment by public** [comment]
Unfortunately I think this is basically unsupported in gRPC in general. The closest that's supported within the protocol is by arranging all your service package to have the same root, e.g. `/foo.services.FooService/`, `/foo.services.BarService/` etc. See this issue for an example: https://github.com/grpc/grpc-web/issues/702

For grpc-web in particular I think the only other option is likely to be to use a sub domain for your API.

**Comment by gitpushdashf** [comment]
Ah, I gotcha. Thank you! It's a shame that wasn't done in the spec. I saw in client.js how endpoint was `http://localhost:port` and was thinking could just add `/api` to the end of that.

**Comment by gitpushdashf** [comment]
I'll close this out for now, but hopefully it helps someone else with the same question. I appreciate your help.
