### ISSUE TITLE
service wsgi-server failed

### ISSUE THREAD

**Issue by RoacherM** [public/sonora#45]
when i try to run service via docker-compose.yml, i ran into error caused by async-timeout, is there any solutions?

Installing dependencies from lock file

  SolverProblemError

  Because aiohttp (3.7.4.post0) depends on async-timeout (>=4.0,<5.0)
   and no versions of aiohttp match >=3.7.4,<3.7.4.post0 || >3.7.4.post0,<4.0.0, aiohttp (>=3.7.4,<4.0.0) requires async-timeout (>=4.0,<5.0).
  So, because sonora depends on both async-timeout (^3.0.1) and aiohttp (^3.7.4), version solving failed.

**Comment by gitpushdashf** [comment]
@public would you be able to take a look at this?

**Comment by gitpushdashf** [comment]
Thank you for merging! I see that CI failed, but to me it doesn't look related. Is there any way you might be able to cut a new release?

**Comment by public** [comment]
Urgh looks like Google have broken my CI again. It's almost like they don't want other people implementing this protocol.

**Comment by RoacherM** [comment]
i used Poetry

T ***@***.***> 于2021年11月30日周二 上午12:08写道：

**Comment by public** [comment]
@gitpushdashf I have uploaded 0.2.1

**Comment by gitpushdashf** [comment]
Great! Although the current version since May 2nd is 0.2.1: https://pypi.org/project/sonora/#history

Would 0.2.2 work?

**Comment by public** [comment]
Oops. Done.
