### ISSUE TITLE
Missing trailers frame in unary response when no trailers metadata is specified

### ISSUE THREAD

**Issue by parabolala** [public/sonora#47]
Current [code](https://github.com/public/sonora/blob/master/sonora/asgi.py#L218-L238) has:

```
       if context._trailing_metadata:
            trailers = context._trailing_metadata

            trailer_message = protocol.pack_trailers(trailers)
            trailer_data = wrap_message(True, False, trailer_message)
        else:
            trailer_data = b""
...
        await send(
            {"type": "http.response.body", "body": message_data, "more_body": True}
        )
        await send(
            {"type": "http.response.body", "body": trailer_data, "more_body": False}
        )
```

This results in no `trailer_data` frame (i.e. nothing) being sent if no `context._trailing_metadata` is specified instead of non-empty frame containing no data. This seems to violate the gRPC-Web expectations in at least some clients (and maybe in the spec?) that the trailers frame should always be present even if it's data is missing. One particular client unhappy with missing trailers is `protobuf-ts` (fails with `trailers missing`). `grpc-dart` mentions a [similar error](https://github.com/grpc/grpc-dart/issues/505). 

I was able to workaround the issue by changeing the above code to:

```
         if context._trailing_metadata:
            trailers = context._trailing_metadata
        else:
            trailers = b""

        trailer_message = protocol.pack_trailers(trailers)
        trailer_data = wrap_message(True, False, trailer_message)
```

**Comment by public** [comment]
Thanks for this bug report. I'll push a fix.

**Comment by public** [comment]
There's an open draft PR for this. Any chance you could check it out and see if it fixes your problem?

I need to re-do the interop tests again because Google keep breaking them :(

**Comment by parabolala** [comment]
I added the repro code at https://github.com/parabolala/sonora-47-repro
