### ISSUE TITLE
Does anyone else want to help maintain this?

### ISSUE THREAD

**Issue by public** [public/sonora#62]
I don't have a lot of time to commit to this project currently but it seems like there are a few people using it. Would any of you be interested in helping maintain it more actively? e.g. Actually doing releases :)

cc @bouk @zykron1 @itsluketwist @mehdipourfar

**Comment by itsluketwist** [comment]
@public - I wouldn't say I'm particularly an expert on the project, but I'm keen to learn more and help maintain it. 👌

**Comment by public** [comment]
I've given you a contributor invite, if you can send me your PyPi username I can set you up on there too :)

**Comment by itsluketwist** [comment]
Same username for pypi. 😄

**Comment by itsluketwist** [comment]
Great, thanks for the access @public ! Happy for me to start going and make a release? 😄

**Comment by public** [comment]
@itsluketwist Assuming the tests actually still pass on master right now, yes :)

I am just re-running them to see if there's a Circle permission issue with repo or something.

**Comment by itsluketwist** [comment]
I had to update some dependencies slightly, but I managed to run them locally. 😄  https://github.com/public/sonora/pull/63

**Comment by public** [comment]
I have setup Circle so it should having working keys to checkout stuff now.

**Comment by public** [comment]
There are some issues with the CI config still but agree the tests seem to pass 👍  Ship it :)

**Comment by itsluketwist** [comment]
Done!
